-- Your SQL goes here
CREATE TABLE IF NOT EXISTS booking (
	id SERIAL NOT NULL PRIMARY KEY,
	name VARCHAR NOT NULL,
	description VARCHAR NOT NULL,
	rooms INTEGER NOT NULL,
	begin TIME NOT NULL,
	end TIME NOT NULL,
	layout INTEGER NOT NULL,
	approved BOOLEAN NOT NULL
)
